# Ingestión de Datos: Archivos CSV

En esta sección aprenderemos a trabajar con archivos CSV (Comma Separated Values), el formato más común para el intercambio de datos estructurados. Utilizaremos la librería **Pandas**, que es el estándar de la industria para manipulación de datos en Python.

In [1]:
import pandas as pd
import numpy as np

## 1. Carga de datos desde archivos locales

Para cargar un CSV local, usamos la función `pd.read_csv()`. 

> **Nota:** Asegúrate de tener el archivo en la ruta correcta. Normalmente los datos crudos se guardan en una carpeta llamada `raw/` o `data/`.

In [2]:
df = pd.read_csv('raw/datos_ejemplo.csv')
df.head()

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0

## 2. Carga de datos desde URLs (Web)

Pandas permite cargar archivos directamente desde una URL. Esto es muy útil para datasets de prueba alojados en GitHub o repositorios públicos.

In [2]:
# Dataset de ejemplo: Flores Iris
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
df_iris = pd.read_csv(url)

print("Primeras 5 filas del dataset Iris:")
df_iris.head()

Primeras 5 filas del dataset Iris:

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [13]:
df_iris.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 7.2 KB

## 3. Exploración y Filtrado Básico

Una vez cargados los datos, podemos realizar operaciones sencillas para entender su estructura.

In [3]:
df_iris['species']

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: str

In [4]:
df_iris.species

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: str

In [5]:
df_iris['species'] == 'setosa'

0       True
1       True
2       True
3       True
4       True
       ...
145    False
146    False
147    False
148    False
149    False
Name: species, Length: 150, dtype: bool

In [12]:
df_iris_setosa_petalo_largo = df_iris[(
    (df_iris['species'] == 'setosa') & 
    (df_iris['sepal_length']>=5) &
    (df_iris['petal_length']>=1)
    )]

In [ ]:
setosa_df = df_iris[df_iris['species'] == 'setosa']

In [4]:
# Información general del DataFrame
print(df_iris.info())

# Filtrar por una condición (ej. solo flores de la especie 'setosa')
setosa_df = df_iris[df_iris['species'] == 'setosa']
print(f"\nNúmero de registros setosa: {len(setosa_df)}")

# Filtrar por valores numéricos (ej. largo de pétalo > 5)
pétalo_largo = df_iris[df_iris['petal_length'] > 5.0]
pétalo_largo.head()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 7.2 KB
None

Número de registros setosa: 50

     sepal_length  sepal_width  petal_length  petal_width     species
83            6.0          2.7           5.1          1.6  versicolor
100           6.3          3.3           6.0          2.5   virginica
101           5.8          2.7           5.1          1.9   virginica
102           7.1          3.0           5.9          2.1   virginica
103           6.3          2.9           5.6          1.8   virginica

## 4. Guardar datos procesados

Después de filtrar o limpiar nuestros datos, es común querer guardarlos en un nuevo archivo CSV.

In [5]:
# Creamos una carpeta 'output' si no existe
import os
if not os.path.exists('output'):
    os.makedirs('output')

# Guardamos el dataframe filtrado
# index=False evita que se guarde la columna de índices automáticos de pandas
setosa_df.to_csv('output/solo_setosa.csv', index=False)
print("Archivo guardado en output/solo_setosa.csv")

Archivo guardado en output/solo_setosa.csv

## 5. Tips adicionales de `read_csv`

A veces los archivos no son perfectos. Aquí algunos parámetros útiles:

- `sep=';'`: Si el separador es punto y coma en vez de coma.
- `encoding='utf-8'` o `'latin-1'`: Para manejar caracteres especiales.
- `usecols=['col1', 'col2']`: Para cargar solo ciertas columnas.
- `nrows=100`: Para cargar solo las primeras 100 filas (útil con archivos gigantes).