# Pandas - Manipulación de datos

# Introducción a Pandas

Pandas es una poderosa herramienta de manipulación y análisis de datos en Python, desarrollada por [Wes McKinney](https://wesmckinney.com/). Inicialmente construida sobre Numpy y ahora compatible con tecnologías como Arrow, Pandas facilita la limpieza y transformación de datos en bruto, convirtiéndolos en formatos estructurados y aptos para el análisis.

Originalmente diseñada para gestionar datos financieros y ofrecer una alternativa a las hojas de cálculo tradicionales (como Microsoft Excel), se ha consolidado como una librería esencial para el procesamiento de datos y la estadística en Python.

## Tipos de Datos en Pandas

Pandas permite trabajar con distintos tipos de datos, entre los que destacan:

- **Datos tabulares:** Tablas con columnas heterogéneas y etiquetas tanto en filas como en columnas.
- **Series temporales:** Estructuras especializadas para el manejo de datos cronológicos.

## Funcionalidades Clave

Entre las principales funcionalidades de Pandas se incluyen:

- **Lectura y escritura de datos:** Soporta múltiples formatos, como CSV, JSON, Excel, bases de datos SQL, Parquet y HDF5, entre otros.
- **Selección y filtrado:** Permite extraer subconjuntos de datos basados en la posición, valores o etiquetas de forma sencilla.
- **Fusión y unión de datos:** Facilita la integración y combinación de diferentes conjuntos de datos.
- **Transformación de datos:** Ofrece herramientas para aplicar funciones tanto de forma global como a través de ventanas móviles.
- **Manipulación de series temporales:** Proporciona métodos especializados para el tratamiento y análisis de datos basados en el tiempo.
- **Visualización:** Incorpora funcionalidades para generar gráficos y explorar visualmente los datos.

## Estructuras de Datos Fundamentales

Pandas se basa en dos objetos principales:

- **Series:** Estructuras unidimensionales similares a listas.
- **DataFrame:** Estructuras bidimensionales que representan tablas de datos.

En resumen, Pandas ofrece las estructuras de datos y las funciones necesarias para transformar y analizar información de manera eficiente, consolidándose como una herramienta indispensable en el ecosistema Python para la ciencia de datos y la estadística.

In [1]:
import pandas as pd
import numpy as np
import sys

pd.__version__

'3.0.1'

# Series en Pandas

Una **Series** es uno de los tipos de datos fundamentales en Pandas. Es similar a un arreglo de NumPy, pero añade la ventaja de tener etiquetas en los ejes, lo que permite indexarla por etiquetas en lugar de usar únicamente posiciones numéricas. Además, una Series no se limita a contener datos numéricos; puede almacenar cualquier tipo de objeto de Python.

## Creación de una Series

Puedes crear una Series a partir de diferentes estructuras de datos (listas, arreglos de NumPy o diccionarios) utilizando el método `pd.Series`.

### Ejemplo: Preparación de Datos

In [2]:
# Definición de datos

labels = ["a", "b", "c"]          # Lista de etiquetas
my_list = [10, 20, 30]            # Lista de valores
arr = np.array([10, 20, 30])      # Arreglo de NumPy
d = {"a": 10, "b": 20, "c": 30}    # Diccionario

In [3]:
# Tamaño en memoria

print(f"Lista 'labels': {sys.getsizeof(labels)} bytes")
print(f"Lista 'my_list': {sys.getsizeof(my_list)} bytes")
print(f"Array NumPy: {arr.nbytes} bytes (solo datos) + {sys.getsizeof(arr)} bytes (objeto completo)")
print(f"Diccionario: {sys.getsizeof(d)} bytes")

Lista 'labels': 88 bytes
Lista 'my_list': 88 bytes
Array NumPy: 24 bytes (solo datos) + 136 bytes (objeto completo)
Diccionario: 184 bytes

### Creación desde una lista

#### 1. Sin especificar etiquetas:

Al crear una Series a partir de una lista, se asignan automáticamente índices numéricos.

In [4]:
my_list

[10, 20, 30]

In [5]:
pd.Series(data=my_list)

0    10
1    20
2    30
dtype: int64

#### 2. Con etiquetas personalizadas:

Puedes especificar etiquetas usando el parámetro `index`.

In [6]:
labels

['a', 'b', 'c']

In [7]:
pd.Series(data=my_list, index=labels)

a    10
b    20
c    30
dtype: int64

#### 3. Sintaxis abreviada

No es obligatorio usar el nombre del parámetro `data`.

In [8]:
pd.Series(my_list, labels)

a    10
b    20
c    30
dtype: int64

#### 4. Creación desde un arreglo de NumPy

In [9]:
# con etiquetas

pd.Series(arr, labels)

a    10
b    20
c    30
dtype: int64

In [10]:
# sin etiquetas

pd.Series(arr)

0    10
1    20
2    30
dtype: int64

#### 5. Creación desde un Diccionario

Al crear una Serie a partir de un diccionario, las claves se usan automáticamente como etiquetas.

In [11]:
d

{'a': 10, 'b': 20, 'c': 30}

In [12]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

#### 6. Serie con datos no numéricos

Una serie puede contener cualquier tipo de dato. Por ejemplo, crear una Series a partir de una lista de letras.

In [13]:
pd.Series(data=labels)

0    a
1    b
2    c
dtype: str

## Indexación y operaciones en una `Series`

El índice es fundamental en una Series, ya que permite acceder a los datos de manera rápida y eficiente, similar al funcionamiento de un diccionario.

In [14]:
# Creación de series

ser1 = pd.Series([1, 2, 3, 4], index=["USA", "Alemania", "Italia", "Japón"])
print(ser1)
print("-------------------------------------------------------------------------")
ser2 = pd.Series([1, 2, 5, 4], index=["USA", "Alemania", "Colombia", "Japón"])
print(ser2)

USA         1
Alemania    2
Italia      3
Japón       4
dtype: int64
-------------------------------------------------------------------------
USA         1
Alemania    2
Colombia    5
Japón       4
dtype: int64

In [ ]:
ser1[0]

In [15]:
# Acceso a elementos

print(ser1["USA"])

1

In [16]:
# Las operaciones también se realizan según el índice

ser1 + ser2

Alemania    4.0
Colombia    NaN
Italia      NaN
Japón       8.0
USA         2.0
dtype: float64

**Nótese que las etiquetas que no se encuentran en ambas resultan en `NaN`.**

# DataFrames

Los **DataFrames** son la estructura de datos más importante en Pandas y están directamente inspirados en el lenguaje de programación R. Se pueden entender como un conjunto de Series que comparten el mismo índice, lo que permite representar y manipular datos en forma de tabla de manera eficiente. Con un DataFrame, tienes la posibilidad de definir tanto los índices (nombres de las filas) como los nombres de las columnas, facilitando la organización y análisis de la información.

In [14]:
# Creación de un DataFrame

from numpy.random import randn

In [15]:
# Iniciar el generador aleatorio para obtener resultados reproducibles

np.random.seed(24)

In [16]:
# Forma rápida de crear una lista de python desde strings

filas = "A B C D E F".split()

filas

['A', 'B', 'C', 'D', 'E', 'F']

In [17]:
# Crear una lista de etiquetas para las columnas

columnas = "W X Y Z".split()

In [18]:
# Crear un dataframe con números aleatorios de 4 columnas y 5 filas

df  =pd.DataFrame(randn(6, 4), filas, columnas)
df

          W         X         Y         Z
A  1.329212 -0.770033 -0.316280 -0.990810
B -1.070816 -1.438713  0.564417  0.295722
C -1.626404  0.219565  0.678805  1.889273
D  0.961538  0.104011 -0.481165  0.850229
E  1.453425  1.057737  0.165562  0.515018
F -1.336936  0.562861  1.392855 -0.063328

## Explorando el DataFrame

Una vez creado el DataFrame, existen varias funciones útiles para obtener información general sobre su estructura y contenido.

In [19]:
# Número de filas y columnas

df.shape

(6, 4)

In [20]:
# Información general de los datos de cada columna

df.info()

<class 'pandas.DataFrame'>
Index: 6 entries, A to F
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   W       6 non-null      float64
 1   X       6 non-null      float64
 2   Y       6 non-null      float64
 3   Z       6 non-null      float64
dtypes: float64(4)
memory usage: 246.0 bytes

In [21]:
# Tipo de datos que existen en las columnas del dataframe

df.dtypes

W    float64
X    float64
Y    float64
Z    float64
dtype: object

In [22]:
# Estadística descriptiva de las columnas numéricas

df.describe()

              W         X         Y         Z
count  6.000000  6.000000  6.000000  6.000000
mean  -0.048330 -0.044095  0.334032  0.416017
std    1.440071  0.910585  0.694102  0.958356
min   -1.626404 -1.438713 -0.481165 -0.990810
25%   -1.270406 -0.551522 -0.195820  0.026434
50%   -0.054639  0.161788  0.364989  0.405370
75%    1.237294  0.477037  0.650208  0.766426
max    1.453425  1.057737  1.392855  1.889273

In [23]:
df.head() # Primeras 5 filas

          W         X         Y         Z
A  1.329212 -0.770033 -0.316280 -0.990810
B -1.070816 -1.438713  0.564417  0.295722
C -1.626404  0.219565  0.678805  1.889273
D  0.961538  0.104011 -0.481165  0.850229
E  1.453425  1.057737  0.165562  0.515018

In [24]:
df.tail() # Últimos 5 elementos

          W         X         Y         Z
B -1.070816 -1.438713  0.564417  0.295722
C -1.626404  0.219565  0.678805  1.889273
D  0.961538  0.104011 -0.481165  0.850229
E  1.453425  1.057737  0.165562  0.515018
F -1.336936  0.562861  1.392855 -0.063328

In [25]:
df.sample(3) # Elementos aleatorios

          W         X         Y         Z
E  1.453425  1.057737  0.165562  0.515018
F -1.336936  0.562861  1.392855 -0.063328
B -1.070816 -1.438713  0.564417  0.295722

## Selección e indexación en DataFrames

Pandas ofrece diversos métodos para acceder y manipular los datos contenidos en un DataFrame. A continuación se muestran ejemplos prácticos de cómo seleccionar columnas, filas, crear nuevas columnas, eliminarlas y aplicar filtros condicionales.

In [26]:
# Acceso a columnas

df["W"]

A    1.329212
B   -1.070816
C   -1.626404
D    0.961538
E    1.453425
F   -1.336936
Name: W, dtype: float64

In [28]:
# Seleccionar dos o más columnas
# Se debe pasar una lista con los nombres de las columnas

df[["W", "Z"]]

          W         Z
A  1.329212 -0.990810
B -1.070816  0.295722
C -1.626404  1.889273
D  0.961538  0.850229
E  1.453425  0.515018
F -1.336936 -0.063328

In [ ]:
df_clean = df[["one", "two"]]

In [29]:
df

          W         X         Y         Z
A  1.329212 -0.770033 -0.316280 -0.990810
B -1.070816 -1.438713  0.564417  0.295722
C -1.626404  0.219565  0.678805  1.889273
D  0.961538  0.104011 -0.481165  0.850229
E  1.453425  1.057737  0.165562  0.515018
F -1.336936  0.562861  1.392855 -0.063328

In [31]:
# Puedo indicar el orden de las columnas

df[["X", "W", "Z"]]

          X         W         Z
A -0.770033  1.329212 -0.990810
B -1.438713 -1.070816  0.295722
C  0.219565 -1.626404  1.889273
D  0.104011  0.961538  0.850229
E  1.057737  1.453425  0.515018
F  0.562861 -1.336936 -0.063328

In [30]:
# Las columnas de un dataframe son solo Series

type(df["W"]) # Tipos de datos

pandas.Series

## Creación de nuevas columnas

In [32]:
df["nueva"] = df["W"] + df["Y"] # Crear una nueva columna
df

          W         X         Y         Z     nueva
A  1.329212 -0.770033 -0.316280 -0.990810  1.012932
B -1.070816 -1.438713  0.564417  0.295722 -0.506399
C -1.626404  0.219565  0.678805  1.889273 -0.947599
D  0.961538  0.104011 -0.481165  0.850229  0.480373
E  1.453425  1.057737  0.165562  0.515018  1.618986
F -1.336936  0.562861  1.392855 -0.063328  0.055919

## Eliminación de columnas

In [33]:
df.drop("nueva", axis=1) # Eliminar una columna

          W         X         Y         Z
A  1.329212 -0.770033 -0.316280 -0.990810
B -1.070816 -1.438713  0.564417  0.295722
C -1.626404  0.219565  0.678805  1.889273
D  0.961538  0.104011 -0.481165  0.850229
E  1.453425  1.057737  0.165562  0.515018
F -1.336936  0.562861  1.392855 -0.063328

In [35]:
# Nótese que si no se guarda en una variable o si no se guarda en una variable no se aplica al dataframe

df

          W         X         Y         Z     nueva
A  1.329212 -0.770033 -0.316280 -0.990810  1.012932
B -1.070816 -1.438713  0.564417  0.295722 -0.506399
C -1.626404  0.219565  0.678805  1.889273 -0.947599
D  0.961538  0.104011 -0.481165  0.850229  0.480373
E  1.453425  1.057737  0.165562  0.515018  1.618986
F -1.336936  0.562861  1.392855 -0.063328  0.055919

In [ ]:
df = df[["W", "X", "Y", "Z"]]

In [36]:
df.drop("nueva", axis="columns", inplace=True)
df

          W         X         Y         Z
A  1.329212 -0.770033 -0.316280 -0.990810
B -1.070816 -1.438713  0.564417  0.295722
C -1.626404  0.219565  0.678805  1.889273
D  0.961538  0.104011 -0.481165  0.850229
E  1.453425  1.057737  0.165562  0.515018
F -1.336936  0.562861  1.392855 -0.063328

In [36]:
# También se pueden eliminar filas de la siguiente manera:

df.drop("E", axis="index", inplace=True)

In [37]:
df

          W         X         Y         Z     nueva
A  1.329212 -0.770033 -0.316280 -0.990810  1.012932
B -1.070816 -1.438713  0.564417  0.295722 -0.506399
C -1.626404  0.219565  0.678805  1.889273 -0.947599
D  0.961538  0.104011 -0.481165  0.850229  0.480373
F -1.336936  0.562861  1.392855 -0.063328  0.055919

In [38]:
# Otra manera de borrar las columnas es:

del df["X"]
df

          W         Y         Z
A  1.329212 -0.316280 -0.990810
B -1.070816  0.564417  0.295722
C -1.626404  0.678805  1.889273
D  0.961538 -0.481165  0.850229
E  1.453425  0.165562  0.515018
F -1.336936  1.392855 -0.063328

## Obtener nombres de columnas y de índices

In [39]:
df.columns # Nombres de las columnas

Index(['W', 'Y', 'Z'], dtype='str')

In [40]:
df.index # Nombres de los índices

Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='str')

## Seleccionando Filas y Columnas

Las dos formas de selección principal son: por etiquetas o por índices.

In [38]:
df

          W         X         Y         Z     nueva
A  1.329212 -0.770033 -0.316280 -0.990810  1.012932
B -1.070816 -1.438713  0.564417  0.295722 -0.506399
C -1.626404  0.219565  0.678805  1.889273 -0.947599
D  0.961538  0.104011 -0.481165  0.850229  0.480373
F -1.336936  0.562861  1.392855 -0.063328  0.055919

In [ ]:
df["W"]

In [41]:
# Por etiquetas

df.loc["A"] # Se seleccionan todos los valores de la fila A

W    1.329212
Y   -0.316280
Z   -0.990810
Name: A, dtype: float64

In [42]:
# Por índices

df.iloc[1] # Se seleccionan los valores de la fila con índice 1

W   -1.070816
Y    0.564417
Z    0.295722
Name: B, dtype: float64

In [43]:
df

          W         Y         Z
A  1.329212 -0.316280 -0.990810
B -1.070816  0.564417  0.295722
C -1.626404  0.678805  1.889273
D  0.961538 -0.481165  0.850229
E  1.453425  0.165562  0.515018
F -1.336936  1.392855 -0.063328

In [44]:
# Seleccionar un subconjunto de filas y columnas

# Mediante etiquetas, se selecciona el elemento que está en la fila=B y Col=Y

df.loc["B", "Y"]

np.float64(0.5644168515196336)

In [45]:
# Mediante etiquetas
# Esta vez se selecciona un subconjunto de datos que están entre filas = A, B y Cols = W, Y

df.loc[["A", "B"], ["W", "Y"]]

          W         Y
A  1.329212 -0.316280
B -1.070816  0.564417

## Selección condicional o filtros

Una característica importante de pandas es la selección condicional usando la notación de corchetes.

In [46]:
df

          W         Y         Z
A  1.329212 -0.316280 -0.990810
B -1.070816  0.564417  0.295722
C -1.626404  0.678805  1.889273
D  0.961538 -0.481165  0.850229
E  1.453425  0.165562  0.515018
F -1.336936  1.392855 -0.063328

In [47]:
# Devuelve una serie con booleanos

df["W"] > 0

A     True
B    False
C    False
D     True
E     True
F    False
Name: W, dtype: bool

In [48]:
df

          W         Y         Z
A  1.329212 -0.316280 -0.990810
B -1.070816  0.564417  0.295722
C -1.626404  0.678805  1.889273
D  0.961538 -0.481165  0.850229
E  1.453425  0.165562  0.515018
F -1.336936  1.392855 -0.063328

In [49]:
# Selecciona las filas donde la columna W es mayor a 0

df[df["W"] > 0]

          W         Y         Z
A  1.329212 -0.316280 -0.990810
D  0.961538 -0.481165  0.850229
E  1.453425  0.165562  0.515018

In [50]:
# Selecciona las filas donde "Z" sea mayor que cero
# y de esas filas escoger los valores de la columna "Y"

df[df["Z"] > 0]["Y"]

B    0.564417
C    0.678805
D   -0.481165
E    0.165562
Name: Y, dtype: float64

Para dos condiciones, se usa booleanos de esta forma:

* | en vez de `or`
* & en vez de `and`
* ~ en vez de `not`

**¡Y RECUERDE USAR PARÉNTESIS!** `💥

In [40]:
df["flag"] = df["W"] > 0

In [42]:
df[~df["flag"]==True]

          W         X         Y         Z     nueva   flag
B -1.070816 -1.438713  0.564417  0.295722 -0.506399  False
C -1.626404  0.219565  0.678805  1.889273 -0.947599  False
F -1.336936  0.562861  1.392855 -0.063328  0.055919  False

In [ ]:
df[]

In [44]:
# Seleccionar las filas donde "W" sea mayor que cero
# y también donde "Y" sea mayor que 0.5

limite_x = -1.5
limite_y = 0.5

df[(df["W"] > limite_x) & (df["Y"] > limite_y)]

          W         X         Y         Z     nueva   flag
B -1.070816 -1.438713  0.564417  0.295722 -0.506399  False
F -1.336936  0.562861  1.392855 -0.063328  0.055919  False

### Búsqueda condicional `.query()`

Los términos de búsqueda condicional o filtros se entregan al método como tipo "string".

In [45]:
df

          W         X         Y         Z     nueva   flag
A  1.329212 -0.770033 -0.316280 -0.990810  1.012932   True
B -1.070816 -1.438713  0.564417  0.295722 -0.506399  False
C -1.626404  0.219565  0.678805  1.889273 -0.947599  False
D  0.961538  0.104011 -0.481165  0.850229  0.480373   True
F -1.336936  0.562861  1.392855 -0.063328  0.055919  False

In [ ]:
# seleccionar todas las filas donde el valor
# que está en la columna "W" sea mayor que 0

df.query("W>0")
#df[df["W"]>0]

          W         Y         Z
A  1.329212 -0.316280 -0.990810
D  0.961538 -0.481165  0.850229
E  1.453425  0.165562  0.515018

In [54]:
# seleccionar las filas donde "W" sea mayor que 0
# y de esas filas escoger los valores de la columna "Y"

df.query("W>0")["Y"]

A   -0.316280
D   -0.481165
E    0.165562
Name: Y, dtype: float64

In [55]:
# seleccionar las filas donde "W" sea mayor que 0
# y de esas filas escoger los valores de las columnas "Y" y "X"


df.query("W>0")[["Y", "Z"]]

          Y         Z
A -0.316280 -0.990810
D -0.481165  0.850229
E  0.165562  0.515018

In [56]:
df

          W         Y         Z
A  1.329212 -0.316280 -0.990810
B -1.070816  0.564417  0.295722
C -1.626404  0.678805  1.889273
D  0.961538 -0.481165  0.850229
E  1.453425  0.165562  0.515018
F -1.336936  1.392855 -0.063328

In [48]:
# para dos condiciones, puede usar | = or y & = and con paréntesis:

# seleccionar las filas donde 'W' sea mayor que cero
# y también donde 'Y' sea mayor que 0.5

# df[(df['W']>0) & (df['Y'] > 0.5)]
df.query("W>-1.5 & Y>0.5")

          W         X         Y         Z     nueva   flag
B -1.070816 -1.438713  0.564417  0.295722 -0.506399  False
F -1.336936  0.562861  1.392855 -0.063328  0.055919  False

## Cambio de columna de indexación

Analicemos algunas características más de la indexación, incluido el restablecimiento del índice o el establecimiento de parámetros.

In [58]:
df

          W         Y         Z
A  1.329212 -0.316280 -0.990810
B -1.070816  0.564417  0.295722
C -1.626404  0.678805  1.889273
D  0.961538 -0.481165  0.850229
E  1.453425  0.165562  0.515018
F -1.336936  1.392855 -0.063328

In [49]:
df[df["W"]>0]

          W         X         Y         Z     nueva  flag
A  1.329212 -0.770033 -0.316280 -0.990810  1.012932  True
D  0.961538  0.104011 -0.481165  0.850229  0.480373  True

Se puede reiniciar el índice con números consecutivos.

In [50]:
df.reset_index() # Reiniciar los índices

  index         W         X         Y         Z     nueva   flag
0     A  1.329212 -0.770033 -0.316280 -0.990810  1.012932   True
1     B -1.070816 -1.438713  0.564417  0.295722 -0.506399  False
2     C -1.626404  0.219565  0.678805  1.889273 -0.947599  False
3     D  0.961538  0.104011 -0.481165  0.850229  0.480373   True
4     F -1.336936  0.562861  1.392855 -0.063328  0.055919  False

In [59]:
df_index = df.reset_index(drop=True) # Reiniciar los índices

In [56]:
df_index_filtrado = df_index[df_index["W"]>0].reset_index(drop=True)

In [57]:
df_index_filtrado

          W         X         Y         Z     nueva  flag
0  1.329212 -0.770033 -0.316280 -0.990810  1.012932  True
1  0.961538  0.104011 -0.481165  0.850229  0.480373  True

**Nótese** que el `index` anterior se convierte en una columna.

Se puede redefinir el índice con los valores de otra columna.

In [64]:
df

          W         X         Y         Z     nueva   flag
A  1.329212 -0.770033 -0.316280 -0.990810  1.012932   True
B -1.070816 -1.438713  0.564417  0.295722 -0.506399  False
C -1.626404  0.219565  0.678805  1.889273 -0.947599  False
D  0.961538  0.104011 -0.481165  0.850229  0.480373   True
F -1.336936  0.562861  1.392855 -0.063328  0.055919  False

In [65]:
# Es MUY importante tener valores que no sean duplicados

df["States"] = ["CA", "NY", "WY", "OR", "CO"]

df

          W         X         Y         Z     nueva   flag States
A  1.329212 -0.770033 -0.316280 -0.990810  1.012932   True     CA
B -1.070816 -1.438713  0.564417  0.295722 -0.506399  False     NY
C -1.626404  0.219565  0.678805  1.889273 -0.947599  False     WY
D  0.961538  0.104011 -0.481165  0.850229  0.480373   True     OR
F -1.336936  0.562861  1.392855 -0.063328  0.055919  False     CO

In [66]:
# Se puede redefinir la columna "States" como el índice

df = df.set_index("States", drop = True)

df

               W         X         Y         Z     nueva   flag
States
CA      1.329212 -0.770033 -0.316280 -0.990810  1.012932   True
NY     -1.070816 -1.438713  0.564417  0.295722 -0.506399  False
WY     -1.626404  0.219565  0.678805  1.889273 -0.947599  False
OR      0.961538  0.104011 -0.481165  0.850229  0.480373   True
CO     -1.336936  0.562861  1.392855 -0.063328  0.055919  False

## Groupby (Agrupación por filas)

El método groupby le permite agrupar filas de datos y llamar a funciones agregadas.

In [67]:
# Crear dataframe desde un diccionario
data = {
    "Company": ["GOOG", "GOOG", "MSFT", "MSFT", "FB", "FB", "GOOG", "MSFT", "FB"],
    "Person": [
        "Sam",
        "Charlie",
        "Amy",
        "Vanessa",
        "Carl",
        "Sarah",
        "John",
        "Randy",
        "David",
    ],
    "Sales": [200, 120, 340, 124, 243, 350, 275, 400, 180],
}

# Conversión del diccionario a dataframe
df = pd.DataFrame(data)
df

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350
6    GOOG     John    275
7    MSFT    Randy    400
8      FB    David    180

Se puede usar el método `.groupby()` para agrupar filas en función de un nombre de columna. Por ejemplo, vamos a agruparnos a partir de la compañía. Esto creará un objeto `DataFrameGroupBy`:

In [63]:
# Agrupar por compañía

df.groupby("Company")

In [64]:
# utilizar los métodos agregados del objeto

df.groupby("Company").mean(numeric_only=True)

              Sales
Company
FB       257.666667
GOOG     198.333333
MSFT     288.000000

In [65]:
# Agrupar por compañía y calcular la desviación estándar

df.groupby("Company").std(numeric_only=True)

              Sales
Company
FB        85.943780
GOOG      77.513440
MSFT     145.161978

In [66]:
# Agrupar por compañía y calcular el mínimo

df.groupby("Company").min(numeric_only=True)

         Sales
Company
FB         180
GOOG       120
MSFT       124

In [67]:
df

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350
6    GOOG     John    275
7    MSFT    Randy    400
8      FB    David    180

In [68]:
# Agrupar por compañía y sumar los elementos que hay excluyendo los NaN

df.groupby("Company").count()

         Person  Sales
Company
FB            3      3
GOOG          3      3
MSFT          3      3

Una de las funciones más poderosas para descripción estadística de un dataframe es `describe()`

In [68]:
df.describe()

            Sales
count    9.000000
mean   248.000000
std    100.879879
min    120.000000
25%    180.000000
50%    243.000000
75%    340.000000
max    400.000000

In [69]:
df.groupby("Company").describe()

        Sales
        count        mean         std    min    25%    50%    75%    max
Company
FB        3.0  257.666667   85.943780  180.0  211.5  243.0  296.5  350.0
GOOG      3.0  198.333333   77.513440  120.0  160.0  200.0  237.5  275.0
MSFT      3.0  288.000000  145.161978  124.0  232.0  340.0  370.0  400.0

In [70]:
# Para cambiar la forma en la que imprime en pantalla
df.groupby("Company").describe().transpose()

Company              FB        GOOG        MSFT
Sales count    3.000000    3.000000    3.000000
      mean   257.666667  198.333333  288.000000
      std     85.943780   77.513440  145.161978
      min    180.000000  120.000000  124.000000
      25%    211.500000  160.000000  232.000000
      50%    243.000000  200.000000  340.000000
      75%    296.500000  237.500000  370.000000
      max    350.000000  275.000000  400.000000

In [71]:
# Si solo se quiere ver por compañía

df.groupby("Company").describe().transpose()["GOOG"]

Sales  count      3.000000
       mean     198.333333
       std       77.513440
       min      120.000000
       25%      160.000000
       50%      200.000000
       75%      237.500000
       max      275.000000
Name: GOOG, dtype: float64

## Pivot Table

La funcionalidad "pivot_table" es muy utilizada y popular en las hojas de cálculo. Esta funcionalidad permite agrupar, ordenar, calcular datos. Para más información sobre pivot table hacer clic [aquí](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.pivot_table.html).

In [69]:
import seaborn as sns

In [70]:
# Se carga el dataset de titanic

titanic = sns.load_dataset("titanic")
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [71]:
# Si se hiciera una pivot_table a mano para obtener el promedio de personas que sobrevivieron por género:

titanic.groupby("sex")[["survived"]].mean()

        survived
sex
female  0.742038
male    0.188908

In [72]:
# Para obtener el promedio de cuántos sobrevivieron por género divididos por clase:

titanic.groupby(["sex", "class", "embark_town"], observed=True)[["survived"]].mean().unstack()

               survived
embark_town   Cherbourg Queenstown Southampton
sex    class
female First   0.976744   1.000000    0.958333
       Second  1.000000   1.000000    0.910448
       Third   0.652174   0.727273    0.375000
male   First   0.404762   0.000000    0.354430
       Second  0.200000   0.000000    0.154639
       Third   0.232558   0.076923    0.128302

* Con el parámetro `observed=True` solo se incluyen las categorías que están presentes en los datos. Evita incluir filas o columnas vacías en el resultado final.

* Con el método `unstack()` se transforma (o "desapila") uno de los niveles del índice en columnas. Cuando se utiliza en el resultado de un groupby() que genera un MultiIndex (por ejemplo, un índice jerárquico basado en "sex" y "class"), `unstack()` convierte uno de esos niveles en columnas para facilitar la visualización y el análisis.

### Usando Pivot Tables

In [ ]:
titanic.pivot_table("survived", index="sex", columns=["class", "embark_town"], observed=True)

class      First    Second     Third
sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

## Concatenar y fusionar

Concatenar y fusionar son las dos formas principales de combinar DataFrames.

In [73]:
df1 = pd.DataFrame(
    {
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
        "C": ["C0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],
    },
    index=[0, 1, 2, 3],
)
df2 = pd.DataFrame(
    {
        "A": ["A4", "A5", "A6", "A7"],
        "B": ["B4", "B5", "B6", "B7"],
        "C": ["C4", "C5", "C6", "C7"],
        "D": ["D4", "D5", "D6", "D7"],
    },
    index=[4, 5, 6, 7],
)
df3 = pd.DataFrame(
    {
        "A": ["A8", "A9", "A10", "A11"],
        "B": ["B8", "B9", "B10", "B11"],
        "C": ["C8", "C9", "C10", "C11"],
        "D": ["D8", "D9", "D10", "D11"],
    },
    index=[8, 9, 10, 11],
)

In [74]:
df1 = pd.DataFrame(
    {
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
        "C": ["C0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],
    },
    index=[0, 1, 2, 3],
)
df2 = pd.DataFrame(
    {
        "A": ["A4", "A5", "A6", "A7"],
        "B": ["B4", "B5", "B6", "B7"],
        "C": ["C4", "C5", "C6", "C7"],
        "D": ["D4", "D5", "D6", "D7"],
    },
    index=[0, 1, 2, 3],
)
df3 = pd.DataFrame(
    {
        "A": ["A8", "A9", "A10", "A11"],
        "B": ["B8", "B9", "B10", "B11"],
        "C": ["C8", "C9", "C10", "C11"],
        "D": ["D8", "D9", "D10", "D11"],
    },
    index=[0, 1, 2, 3],
)

In [78]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [79]:
df2

    A   B   C   D
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [80]:
df3

     A    B    C    D
0   A8   B8   C8   D8
1   A9   B9   C9   D9
2  A10  B10  C10  D10
3  A11  B11  C11  D11

### Concatenación

* La concatenación básicamente combina DataFrames. Se debe tener en cuenta que las dimensiones deben coincidir a lo largo del eje con el que se está concatenando.

* La concatenación se hace con dataframes de diferentes índices.

* Puede usar `.concat()` y pasar una lsita de DataFrames para concatenar juntos.

In [76]:
pd.concat([df1, df2, df3], axis = "index").reset_index(drop=True)

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

También se puede concatenar el DataFrame horizontalmente.
**Nota:** como no coinciden los index, observa lo que ocurre.

In [79]:
pd.concat([df1, df2, df3], axis="columns")

      A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

### Fusión (merging)

La fusión `merge()` le permite fusionar DataFrames juntos utilizando una lógica similar a la combinación de Tablas SQL. Por ejemplo:

In [84]:
# DataFrames de ejemplo para merging
left = pd.DataFrame(
    {
        "Producto": ["Arepas", "Banano", "Cafe", "Leche"],
        "Tienda": [1, 2, 1, 1],
        "Ventas": [100, 200, 50, 10],
    }
)

right = pd.DataFrame(
    {
        "Producto": ["Arepas", "Banano", "Cafe", "huevo"],
        "Tienda": [1, 2, 1, 1],
        "Inventario": [50, 100, 75, 10],
    }
)

In [85]:
left

  Producto  Tienda  Ventas
0   Arepas       1     100
1   Banano       2     200
2     Cafe       1      50
3    Leche       1      10

In [86]:
right

  Producto  Tienda  Inventario
0   Arepas       1          50
1   Banano       2         100
2     Cafe       1          75
3    huevo       1          10

In [87]:
# how="inner" utiliza la intersección de las claves de ambos marcos,
# similar a una combinación interna de SQL.

pd.merge(left, right, how="inner", on="Producto")

  Producto  Tienda_x  Ventas  Tienda_y  Inventario
0   Arepas         1     100         1          50
1   Banano         2     200         2         100
2     Cafe         1      50         1          75

In [88]:
pd.merge(left, right, how="left", on="Producto")

  Producto  Tienda_x  Ventas  Tienda_y  Inventario
0   Arepas         1     100       1.0        50.0
1   Banano         2     200       2.0       100.0
2     Cafe         1      50       1.0        75.0
3    Leche         1      10       NaN         NaN

In [89]:
pd.merge(left, right, how="right", on="Producto")

  Producto  Tienda_x  Ventas  Tienda_y  Inventario
0   Arepas       1.0   100.0         1          50
1   Banano       2.0   200.0         2         100
2     Cafe       1.0    50.0         1          75
3    huevo       NaN     NaN         1          10

In [91]:
pd.merge(left, right, how="outer", on="Producto")

  Producto  Tienda_x  Ventas  Tienda_y  Inventario
0   Arepas       1.0   100.0       1.0        50.0
1   Banano       2.0   200.0       2.0       100.0
2     Cafe       1.0    50.0       1.0        75.0
3    Leche       1.0    10.0       NaN         NaN
4    huevo       NaN     NaN       1.0        10.0

Un ejemplo más complicado:

* **Natural join:** para mantener solo las filas que coinciden con los marcos de datos, especifique el argumento **how = ‘inner’**.
* **Full outer join:** para mantener todas las filas de ambos dataframe, especifique **how = ‘OUTER’**.
* **Left outer join:** para incluir todas las filas de su dataframe x y solo aquellas de y que coincidan, especifique **how=‘left’**.
* **Right outer join:** para incluir todas las filas de su dataframe y y solo aquellas de x que coincidan, especifique **how=‘right’**.


Imagen para entender los tipos de merge [aquí](https://miro.medium.com/v2/resize:fit:752/0*ZGDgg-0SznYlwiij.png)

In [84]:
left = pd.DataFrame(
    {
        "Producto": ["Arepas", "Leche", "Cafe"],
        "Tienda": [1, 2, 1],
        "Ventas": [100, 200, 50],
    }
)

right = pd.DataFrame(
    {
        "Producto": ["Arepas", "Banano", "Cafe"],
        "Tienda": [1, 2, 1],
        "Inventario": [50, 100, 75],
    }
)

In [85]:
left

  Producto  Tienda  Ventas
0   Arepas       1     100
1    Leche       2     200
2     Cafe       1      50

In [86]:
right

  Producto  Tienda  Inventario
0   Arepas       1          50
1   Banano       2         100
2     Cafe       1          75

#### Claves comunes entre tablas

In [ ]:
# Fusionando comparando las mismas claves que tengan comunes

pd.merge(left, right, on=["Producto"])

  Producto  Tienda_x  Ventas  Tienda_y  Inventario
0   Arepas         1     100         1          50
1     Cafe         1      50         1          75

#### Fusionando totalmente las dos tablas con las claves

In [88]:
pd.merge(left, right, how="outer", on=["Producto"])

  Producto  Tienda_x  Ventas  Tienda_y  Inventario
0   Arepas       1.0   100.0       1.0        50.0
1   Banano       NaN     NaN       2.0       100.0
2     Cafe       1.0    50.0       1.0        75.0
3    Leche       2.0   200.0       NaN         NaN

#### Fusionando usando las claves de la tabla right

In [92]:
print("Tabla left")
print(left)
print("-------------------------------------------------------------------------")

print("Tabla right")
print(right)

Tabla left
  Producto  Tienda  Ventas
0   Arepas       1     100
1   Banano       2     200
2     Cafe       1      50
3    Leche       1      10
-------------------------------------------------------------------------
Tabla right
  Producto  Tienda  Inventario
0   Arepas       1          50
1   Banano       2         100
2     Cafe       1          75
3    huevo       1          10

In [90]:
pd.merge(left, right, how="right", on=["Producto"])

  Producto  Tienda_x  Ventas  Tienda_y  Inventario
0   Arepas       1.0   100.0         1          50
1   Banano       NaN     NaN         2         100
2     Cafe       1.0    50.0         1          75

#### Fusionando usando las claves de la tabla left

In [91]:
pd.merge(left, right, how="left", on=["Producto"])

  Producto  Tienda_x  Ventas  Tienda_y  Inventario
0   Arepas         1     100       1.0        50.0
1    Leche         2     200       NaN         NaN
2     Cafe         1      50       1.0        75.0

---

# Datos categóricos

* Con Pandas, la búsqueda en datos categóricos es mucho más rápida.
* Ocupan menos memoria que si los datos están como string.
* Se pueden tener datos categóricos ordinales.

Más información de datos categóricos en:

https://pandas.pydata.org/pandas-docs/stable/user_guide/categorical.html

In [92]:
# Creación

cate = pd.Series(["manzana", "banano", "corozo", "manzana", "pera"], dtype="category")
cate

0    manzana
1     banano
2     corozo
3    manzana
4       pera
dtype: category
Categories (4, str): ['banano', 'corozo', 'manzana', 'pera']

In [93]:
df.describe()

            Sales
count    9.000000
mean   248.000000
std    100.879879
min    120.000000
25%    180.000000
50%    243.000000
75%    340.000000
max    400.000000

In [93]:
cate.describe()

count           5
unique          4
top       manzana
freq            2
dtype: object

In [94]:
# Creando primero los datos y luego convirtiéndolos en categóricos

# Creando primero los datos y luego convirtiéndolos en categóricos
df_cate = pd.DataFrame({"Fruta": ["manzana", "banano", "corozo", "manzana", "pera"]})
df_cate

     Fruta
0  manzana
1   banano
2   corozo
3  manzana
4     pera

In [95]:
df_cate.dtypes

Fruta    str
dtype: object

In [97]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Company  9 non-null      str
 1   Person   9 non-null      str
 2   Sales    9 non-null      int64
dtypes: int64(1), str(2)
memory usage: 421.0 bytes

In [96]:
df_cate.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Fruta   5 non-null      str
dtypes: str(1)
memory usage: 202.0 bytes

In [98]:
df_cate["Fruta2"] = df_cate["Fruta"].astype("category")
df_cate

     Fruta   Fruta2
0  manzana  manzana
1   banano   banano
2   corozo   corozo
3  manzana  manzana
4     pera     pera

In [98]:
df_cate.dtypes

Fruta          str
Fruta2    category
dtype: object

In [99]:
# Crear los datos categóricos desde a declaración de los datos
df_cate = pd.DataFrame({"A": list("abca"), "B": list("bccd")}, dtype="category")
df_cate

   A  B
0  a  b
1  b  c
2  c  c
3  a  d

In [100]:
df_cate.dtypes

A    category
B    category
dtype: object

In [101]:
df_cate.describe()

        A  B
count   4  4
unique  3  3
top     a  c
freq    2  2

# Categóricos Ordinales

In [100]:
# creación de dataframe con datos
df_cate = pd.DataFrame({"A": list("abca"), "B": list("bccd")})
df_cate

   A  B
0  a  b
1  b  c
2  c  c
3  a  d

In [101]:
# verifico tipo de datos
df_cate.dtypes

A    str
B    str
dtype: object

In [102]:
# definición de los tipos de datos y que están en orden

df_cate["A"] = pd.Categorical(
    df_cate["A"], categories=["a", "b", "c", "d"], ordered=True
)

df_cate

   A  B
0  a  b
1  b  c
2  c  c
3  a  d

In [103]:
df_cate["A"]

0    a
1    b
2    c
3    a
Name: A, dtype: category
Categories (4, str): ['a' < 'b' < 'c' < 'd']

In [106]:
# verificar los tipos de datos
df_cate.dtypes

A    category
B         str
dtype: object

In [107]:
# Los datos no tienen que ser strings para que sean categóricos

s = pd.Series([1, 2, 3, 1], dtype="category")
s

0    1
1    2
2    3
3    1
dtype: category
Categories (3, int64): [1, 2, 3]

In [108]:
# Las únicas categorías válidas de la serie serán: [2, 3, 1]
# Al usar `ordered=True`, se indica que estas categorías tienen un orden definido, lo que afecta las operaciones de comparación
# y clasificación

s = s.cat.set_categories([2, 3, 1], ordered=True)
s

0    1
1    2
2    3
3    1
dtype: category
Categories (3, int64): [2 < 3 < 1]

# Correción de tipos de datos (casting)

Cuando se trabaja con datos, es posible que se encuentre con un DataFrame donde el tipo de datos de una columna no es la correcta. Los tipos de datos son principalmente: numéricos, categóricos nominales, categóricos ordinales, booleanos, fechas y tiempos, texto.

Se debe convertir los tipos de datos para que sean apropiados para el tipo de datos que representan. Por ejemplo, es posible que desee convertir una columna de strings que representan números en números enteros o flotantes. O puede tener una columna de números que representan fechas, pero que pandas no reconoce como fechas.

**Nota: al convertir los datos a su forma correcta, normalmente hace que los DataFrames sean mucho más pequeños en la memoria, lo que los hace más eficientes de usar.**

In [104]:
import seaborn as sns  # importar la librería seaborn

titanic = sns.load_dataset("titanic")
titanic.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 100.4 KB

In [ ]:
cols_categoricas_nom = ["sex", "embarked", "who", "embark_town"]
cols_categoricas_ord = ["pclass", "deck"]
cols_numericas = ["age", "fare"]

df[cols_numericas] = df[cols_numericas].astype("float")
df[cols_categoricas_nom] = df[cols_categoricas_nom].astype("category")
df[cols_categoricas_ord] = df[cols_categoricas_ord].astype("category")

In [105]:
titanic.sample(5)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
725,0,3,male,20.0,0,0,8.6625,S,Third,man,True,NaN,Southampton,no,True
777,1,3,female,5.0,0,0,12.4750,S,Third,child,False,NaN,Southampton,yes,True
647,1,1,male,56.0,0,0,35.5000,C,First,man,True,A,Cherbourg,yes,True
637,0,2,male,31.0,1,1,26.2500,S,Second,man,True,NaN,Southampton,no,False
572,1,1,male,36.0,0,0,26.3875,S,First,man,True,E,Southampton,yes,True

## Casting variables categóricas nominales

In [106]:
# convertir la columna sex, embarked, who, embark_town en categóricas
cols_categoricas_nom = ["sex", "embarked", "who", "embark_town"]

# ver los datos únicos de las columnas_categoricas_nom
for columna in cols_categoricas_nom:
    print(f"Valores únicos en {columna}: {titanic[columna].unique()}")

Valores únicos en sex: <ArrowStringArray>
['male', 'female']
Length: 2, dtype: str
Valores únicos en embarked: <ArrowStringArray>
['S', 'C', 'Q', nan]
Length: 4, dtype: str
Valores únicos en who: <ArrowStringArray>
['man', 'woman', 'child']
Length: 3, dtype: str
Valores únicos en embark_town: <ArrowStringArray>
['Southampton', 'Cherbourg', 'Queenstown', nan]
Length: 4, dtype: str

In [107]:
titanic[cols_categoricas_nom] = titanic[cols_categoricas_nom].astype("category")

# ver los datos únicos de las columnas_categoricas_nom
for columna in cols_categoricas_nom:
    print(f"Valores únicos en {columna}: {titanic[columna].unique()}")

Valores únicos en sex: ['male', 'female']
Categories (2, str): ['female', 'male']
Valores únicos en embarked: ['S', 'C', 'Q', NaN]
Categories (3, str): ['C', 'Q', 'S']
Valores únicos en who: ['man', 'woman', 'child']
Categories (3, str): ['child', 'man', 'woman']
Valores únicos en embark_town: ['Southampton', 'Cherbourg', 'Queenstown', NaN]
Categories (3, str): ['Cherbourg', 'Queenstown', 'Southampton']

## Casting variables categóricas ordinales

In [113]:
cols_categoricas_ord = ["pclass", "deck"]

for columna in cols_categoricas_ord:
    print(f"Valores únicos en {columna}: {titanic[columna].unique()}")

Valores únicos en pclass: [3 1 2]
Valores únicos en deck: [NaN, 'C', 'E', 'G', 'D', 'A', 'B', 'F']
Categories (7, str): ['A', 'B', 'C', 'D', 'E', 'F', 'G']

In [114]:
titanic["pclass"] = pd.Categorical(
    titanic["pclass"], categories=[3, 2, 1], ordered=True
)

titanic["deck"] = pd.Categorical(
    titanic["deck"], categories=list("ABCDEFG"), ordered=True
)

In [115]:
for columna in cols_categoricas_ord:
    print(f"Valores únicos en {columna}: {titanic[columna].unique()}")

Valores únicos en pclass: [3, 1, 2]
Categories (3, int64): [3 < 2 < 1]
Valores únicos en deck: [NaN, 'C', 'E', 'G', 'D', 'A', 'B', 'F']
Categories (7, str): ['A' < 'B' < 'C' < 'D' < 'E' < 'F' < 'G']

## Casting variables booleanas

In [116]:
columnas_bool = ["alive", "alone", "survived"]

titanic[columnas_bool] = titanic[columnas_bool].astype("bool")

## Resultado del casting

In [117]:
titanic.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    bool
 1   pclass       891 non-null    category
 2   sex          891 non-null    category
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    category
 8   class        891 non-null    category
 9   who          891 non-null    category
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    category
 13  alive        891 non-null    bool
 14  alone        891 non-null    bool
dtypes: bool(4), category(7), float64(2), int64(2)
memory usage: 38.0 KB

# Datos faltantes

In [108]:
# data frame con algunos datos faltantes
# NaN = Not a Number
df = pd.DataFrame({"A": [1, 2, np.nan], "B": [5, np.nan, np.nan], "C": [1, 2, 3]})
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [ ]:
df["A"]>0

In [119]:
# Detectar si faltan datos

df.isna()

       A      B      C
0  False  False  False
1  False   True  False
2   True   True  False

In [120]:
# Verificar si hay datos faltantes por columna

df.isna().sum()

A    1
B    2
C    0
dtype: int64

In [110]:
# Eliminar datos faltantes

df.dropna(axis="index")

     A    B  C
0  1.0  5.0  1

In [122]:
# eliminar las filas que tengas 2 o mas valores NaN
df.dropna(thresh=2)

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [123]:
# Llenar los datos faltantes con el dato que nos interese
df.fillna(value="Llenar Valores")  # llenar los espacios con un string
# puede ser una palabra, numero , etc

                A               B  C
0             1.0             5.0  1
1             2.0  Llenar Valores  2
2  Llenar Valores  Llenar Valores  3

In [124]:
# Llenar los datos faltantes con el dato que nos interese
df.fillna(value=99)  # llenar los espacios con un numero

      A     B  C
0   1.0   5.0  1
1   2.0  99.0  2
2  99.0  99.0  3

In [125]:
# Llenar los datos faltantes con el promedio de esa columna
df["A"].fillna(value=df["A"].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

# Datos únicos

In [112]:
# crear un dataframe
df = pd.DataFrame(
    {
        "col1": [1, 2, 3, 4],
        "col2": [444, 555, 666, 444],
        "col3": ["abc", "def", "ghi", "xyz"],
    }
)
df

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [113]:
# valores únicos de la columna col2
df["col2"].unique()

array([444, 555, 666])

In [114]:
# Numero de valores únicos en el dataframe
df["col2"].nunique()

3

In [115]:
# contar cuanto se repiten cada uno de los valores
df["col2"].value_counts(1)

col2
444    0.50
555    0.25
666    0.25
Name: proportion, dtype: float64

# Datos duplicados

In [118]:
datos = {
    "nombre": ["Jaime", "Juan", "Roberto", "Juan"],
    "edad": [18, 20, 22, 20],
    "trabajo": ["Asistente", "Manager", "Cientifico", "Manager"],
}
df_dup = pd.DataFrame(datos)
df_dup

    nombre  edad     trabajo
0    Jaime    18   Asistente
1     Juan    20     Manager
2  Roberto    22  Cientifico
3     Juan    20     Manager

In [119]:
# método para detectar los datos duplicados
# me sirve para ver si existen registros duplicados
df_dup.duplicated()

0    False
1    False
2    False
3     True
dtype: bool

In [120]:
# Contar cuantos datos duplicados existen
df_dup.duplicated().sum()

np.int64(1)

In [ ]:
# Para remover los datos duplicados
df_dup.drop_duplicates()

    nombre  edad     trabajo
0    Jaime    18   Asistente
1     Juan    20     Manager
2  Roberto    22  Cientifico

In [123]:
df_dup

    nombre  edad     trabajo
0    Jaime    18   Asistente
1     Juan    20     Manager
2  Roberto    22  Cientifico
3     Juan    20     Manager

In [122]:
# El método drop_duplicates entrega el data frame sin duplicados
# Pero la función no es inplace, osea que el dataframe original sigue igual
df_dup

    nombre  edad     trabajo
0    Jaime    18   Asistente
1     Juan    20     Manager
2  Roberto    22  Cientifico
3     Juan    20     Manager

In [135]:
df_dup.drop_duplicates(inplace=True)
df_dup

    nombre  edad     trabajo
0    Jaime    18   Asistente
1     Juan    20     Manager
2  Roberto    22  Cientifico

# Outliers

Una de las formas de eliminar los outliers es identificando cuál será el rango en el que queremos nuestros datos y limitar los datos entre ese rango.

In [124]:
edad = titanic["age"]
edad

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [137]:
# Cual es la edad maxima
edad.max()

np.float64(80.0)

In [138]:
# Cual es la edad Minima
edad.min()

np.float64(0.42)

Un ejercicio sencillo puede ser delimitar las edades entre 1 y 50 años.

In [139]:
edad = edad.clip(lower=1, upper=50)

In [140]:
edad.max()

np.float64(50.0)

In [141]:
edad.min()

np.float64(1.0)

# Tablas de contingencia

In [142]:
# Crear Datos
data = pd.DataFrame(
    {
        "gender": [
            "male",
            "male",
            "female",
            "female",
            "male",
            "female",
            "male",
            "female",
        ],
        "education_level": [
            "high school",
            "college",
            "college",
            "graduate",
            "high school",
            "graduate",
            "college",
            "graduate",
        ],
        "city": [
            "Boston",
            "Boston",
            "Miami",
            "Boston",
            "Miami",
            "Boston",
            "Miami",
            "Miami",
        ],
        "score": [75, 82, 88, 95, 69, 92, 78, 85],
    }
)

data

   gender education_level    city  score
0    male     high school  Boston     75
1    male         college  Boston     82
2  female         college   Miami     88
3  female        graduate  Boston     95
4    male     high school   Miami     69
5  female        graduate  Boston     92
6    male         college   Miami     78
7  female        graduate   Miami     85

Una **tabla de contingencia** (o tabla cruzada) es una herramienta que resume la relación entre dos o más variables categóricas, mostrando la frecuencia (o porcentaje) de ocurrencia de cada combinación de categorías en una forma tabular. En Pandas, se utiliza comúnmente para realizar análisis exploratorios y detectar posibles asociaciones o dependencias entre variables.

Por ejemplo, la función `pd.crosstab()` permite generar fácilmente una tabla de contingencia. Esto es muy útil para identificar patrones en los datos, como la distribución de pasajeros por clase y sexo en el dataset del Titanic, entre otros usos.

In [126]:
# Crear Datos
data = pd.DataFrame(
    {
        "gender": [
            "male",
            "male",
            "female",
            "female",
            "male",
            "female",
            "male",
            "female",
        ],
        "education_level": [
            "high school",
            "college",
            "college",
            "graduate",
            "high school",
            "graduate",
            "college",
            "graduate",
        ],
        "city": [
            "Boston",
            "Boston",
            "Miami",
            "Boston",
            "Miami",
            "Boston",
            "Miami",
            "Miami",
        ],
        "score": [75, 82, 88, 95, 69, 92, 78, 85],
    }
)

data

   gender education_level    city  score
0    male     high school  Boston     75
1    male         college  Boston     82
2  female         college   Miami     88
3  female        graduate  Boston     95
4    male     high school   Miami     69
5  female        graduate  Boston     92
6    male         college   Miami     78
7  female        graduate   Miami     85

In [127]:
pd.crosstab(data["gender"], data["education_level"], margins=True)

education_level  college  graduate  high school  All
gender
female                 1         3            0    4
male                   2         0            2    4
All                    3         3            2    8

In [128]:
# Tabla de contingencia de Genero, nivel de educación y ciudad
pd.crosstab([data["gender"], data["education_level"]], data["city"], margins=True)

city                    Boston  Miami  All
gender education_level
female college               0      1    1
       graduate              2      1    3
male   college               1      1    2
       high school           1      1    2
All                          4      4    8

In [145]:
# Puntuación promedio por género y nivel de educación

pd.crosstab(
    data["gender"], data["education_level"], values=data["score"], aggfunc="mean"
)

education_level  college   graduate  high school
gender
female              88.0  90.666667          NaN
male                80.0        NaN         72.0

# Métodos y funciones en Pandas

Todos los métodos de los dataframe en pandas se pueden encontrar en:

http://pandas.pydata.org/pandas-docs/stable/reference/frame.html

## Métodos de información general

In [146]:
data = sns.load_dataset("mpg")

data.info()

<class 'pandas.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    str
 8   name          398 non-null    str
dtypes: float64(4), int64(3), str(2)
memory usage: 28.1 KB

In [147]:
data.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [148]:
data.describe()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year
count,398.000000,398.000000,398.000000,392.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,104.469388,2970.424623,15.568090,76.010050
std,7.815984,1.701004,104.269838,38.491160,846.841774,2.757689,3.697627
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000
25%,17.500000,4.000000,104.250000,75.000000,2223.750000,13.825000,73.000000
50%,23.000000,4.000000,148.500000,93.500000,2803.500000,15.500000,76.000000
75%,29.000000,8.000000,262.000000,126.000000,3608.000000,17.175000,79.000000
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000

In [149]:
data.describe(include="all") # Incluye varibales categóricas

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
count,398.000000,398.000000,398.000000,392.000000,398.000000,398.000000,398.000000,398,398
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,305
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,usa,ford pinto
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,249,6
mean,23.514573,5.454774,193.425879,104.469388,2970.424623,15.568090,76.010050,NaN,NaN
std,7.815984,1.701004,104.269838,38.491160,846.841774,2.757689,3.697627,NaN,NaN
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000,NaN,NaN
25%,17.500000,4.000000,104.250000,75.000000,2223.750000,13.825000,73.000000,NaN,NaN
50%,23.000000,4.000000,148.500000,93.500000,2803.500000,15.500000,76.000000,NaN,NaN
75%,29.000000,8.000000,262.000000,126.000000,3608.000000,17.175000,79.000000,NaN,NaN
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000,NaN,NaN

In [150]:
# Describir una sola columna

data["cylinders"].describe()

count    398.000000
mean       5.454774
std        1.701004
min        3.000000
25%        4.000000
50%        4.000000
75%        8.000000
max        8.000000
Name: cylinders, dtype: float64

# Estadística descriptiva

Se pueden calcular estadísticos de medida central, simetría, momentos, etc.

La información oficial de estadística se encunetra en este enlace:

http://pandas.pydata.org/pandas-docs/stable/reference/frame.html#computations-descriptive-stats

**IMPORTANTE:** Los cálculos de las medidas estadísticas se hacen siempre en columndas. Es algo predeterminado. Si se quiere hacer por filas, se debe especificar dentro de los métodos el parámetro axis=1.

In [151]:
data.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='str')

In [152]:
x = data["mpg"]

In [153]:
x.mean()

np.float64(23.514572864321607)

In [154]:
data.mean(numeric_only=True)

mpg               23.514573
cylinders          5.454774
displacement     193.425879
horsepower       104.469388
weight          2970.424623
acceleration      15.568090
model_year        76.010050
dtype: float64

In [155]:
x.min()

np.float64(9.0)

In [156]:
x.mode()

0    13.0
Name: mpg, dtype: float64

## Medidas de asimetría

**Asimetria de Fisher (skewness)**

La asimetría es la medida que indica la simetría de la distribución de una variable respecto a la media aritmética, sin necesidad de hacer la representación gráfica. Los coeficientes de asimetría indican si hay el mismo número de elementos a la izquierda y derecha de la media.

Existen tres tipos de curva de distribución según su asimetría:

* **Asimetría negativa:** la cola de la distribución se alarga para valores inferiores a la media.
* **Simétrica:** hay el mismo número de elementos a izquierda y derecha de la media. En este caso, coinciden la media, la mediana y la moda. La distribución se adapta a la forma de la campana de Gauss, o distribución normal.
* **Asimetría positiva:** la cola de la distribución se alarga para valores superiores a la media.

In [157]:
x.skew()

np.float64(0.45706634399491913)

In [158]:
data.skew(numeric_only=True)

mpg             0.457066
cylinders       0.526922
displacement    0.719645
horsepower      1.087326
weight          0.531063
acceleration    0.278777
model_year      0.011535
dtype: float64

## Curtosis

Esta medida determina el grado de concentración que presentan los valores en la región central de la distribución. Por medio del Coeficiente de Curtosis, podemos identificar si existe una gran concentración de valores (Leptocúrtica), una concentración normal (Mesocúrtica) ó una baja concentración (Platicúrtica).

In [159]:
data.kurtosis(numeric_only=True)

mpg            -0.510781
cylinders      -1.376662
displacement   -0.746597
horsepower      0.696947
weight         -0.785529
acceleration    0.419497
model_year     -1.181232
dtype: float64

# Transformación de variables

## Columnas Dummy

Convertir variables categóricas a numéricas.

In [160]:
# crear datos categóricos

raw_data = {
    "first_name": ["Jason", "Molly", "Tina", "Jake", "Amy"],
    "last_name": ["Miller", "Jacobson", "Ali", "Milner", "Cooze"],
    "sex": ["male", "female", "male", "female", "female"],
}
df = pd.DataFrame(raw_data, columns=["first_name", "last_name", "sex"])
df

  first_name last_name     sex
0      Jason    Miller    male
1      Molly  Jacobson  female
2       Tina       Ali    male
3       Jake    Milner  female
4        Amy     Cooze  female

In [161]:
# Crear un set de variables dummy para la columna sex

df_sex = pd.get_dummies(df["sex"])
df_sex

   female   male
0   False   True
1    True  False
2   False   True
3    True  False
4    True  False

In [162]:
# Unir los dos dataframes

df_new = df.join(df_sex)

df_new

  first_name last_name     sex  female   male
0      Jason    Miller    male   False   True
1      Molly  Jacobson  female    True  False
2       Tina       Ali    male   False   True
3       Jake    Milner  female    True  False
4        Amy     Cooze  female    True  False

# Leer y guardar datos

Pandas puede leer una variedad de tipos de archivos usando sus métodos `pd.read_`

* csv
* parquet (**formato recomendado**)
* excel
* json
* html
* sql

In [ ]:
df = pd.DataFrame({
    "ID": [1, 2, 3, 4, 5],
    "Nombre": ["Ana", "Beto", "Carla", "Daniel", "Elena"],
    "Puntaje": [95, 80, 77, 91, 88]
})

print("DataFrame Original:")
print(df)

DataFrame Original:
   ID  Nombre  Puntaje
0   1     Ana       95
1   2    Beto       80
2   3   Carla       77
3   4  Daniel       91
4   5   Elena       88

In [4]:
# 1. Guardar como CSV (archivo de texto plano)
df.to_csv("output/datos.csv", index=False)

# 2. Guardar como Excel
df.to_excel("output/datos.xlsx", index=False)

# 3. Guardar como Parquet (formato columnar)
df.to_parquet("output/datos.parquet", index=False)

In [5]:
import os

tamanio_csv = os.path.getsize("output/datos.csv")
tamanio_excel = os.path.getsize("output/datos.xlsx")
tamanio_parquet = os.path.getsize("output/datos.parquet")

print(f"Tamaño CSV    : {tamanio_csv} bytes")
print(f"Tamaño Excel  : {tamanio_excel} bytes")
print(f"Tamaño Parquet: {tamanio_parquet} bytes")

Tamaño CSV    : 71 bytes
Tamaño Excel  : 4967 bytes
Tamaño Parquet: 2300 bytes

* **CSV** suele ser más grande que Parquet, porque no aplica compresión ni guarda metadatos de tipos de datos.

* **Excel** tiende a ser más grande que CSV (con un dataset muy simple puede quedar similar, pero suele aumentar con hojas y formato).

* **Parquet** suele ser mucho más pequeño si los datos se pueden comprimir bien. Además, conserva los tipos de datos de forma nativa y ofrece lectura/escritura eficiente para análisis.

# Créditos

Este notebook fue desarrollado con base en este repositorio:

https://github.com/dpalacioj/DataAI-Fundamentos-Aplicaciones/tree/main


Se realizaron algunas modificaciones, complementos, etc.

# Referencias

* https://joserzapata.github.io/courses/python-ciencia-datos/pandas/
* https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html
* [Pandas Basic Cheat Sheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/PandasPythonForDataScience.pdf)